#!/bin/sh

[ "$INIT" ] || exit 0

uci set rnas.config=rnas
uci set rnas.config.enabled=0
uci set rnas.config.protocol=pppoe
uci set rnas.config.interface=br-lan
uci set rnas.config.thread_count=4

uci set rnas.radius=radius
uci set rnas.radius.server=192.168.1.1
uci set rnas.radius.secret=testing123
uci set rnas.radius.auth_port=1812
uci set rnas.radius.acct_port=1813
uci set rnas.radius.coa_port=3799
uci set rnas.radius.timeout=30
uci set rnas.radius.retries=3
uci set rnas.radius.use_radius=1
uci set rnas.radius.use_accounting=1
uci set rnas.radius.interim_interval=300

uci set rnas.pppoe=pppoe
uci set rnas.pppoe.enabled=1
uci set rnas.pppoe.mtu=1492
uci set rnas.pppoe.mru=1492

uci set rnas.ipoe=ipoe
uci set rnas.ipoe.enabled=0
uci set rnas.ipoe.mode=L2

uci set rnas.l2tp=l2tp
uci set rnas.l2tp.enabled=0
uci set rnas.l2tp.port=1701

uci set rnas.pptp=pptp
uci set rnas.pptp.enabled=0
uci set rnas.pptp.port=1723
uci set rnas.pptp.mppe=1

uci set rnas.sstp=sstp
uci set rnas.sstp.enabled=0
uci set rnas.sstp.port=443

uci set rnas.ip_pool=ip_pool
uci add_list rnas.ip_pool.pool=10.0.0.2-10.0.0.254
uci set rnas.ip_pool.gw_pool_address=10.0.0.1
uci set rnas.ip_pool.dns1=8.8.8.8
uci set rnas.ip_pool.dns2=8.8.4.4

uci commit rnas

exit 0
